insert into public.youtube_queries (query_text, priority, is_active, status)
values
  ('reaction videos', 1, true, 'pending'),
  ('reaction videos youtube', 2, true, 'pending'),
  ('roast reactions', 3, true, 'pending'),
  ('roast reactions youtube', 4, true, 'pending'),
  ('cringe compilations', 5, true, 'pending'),
  ('cringe compilations youtube', 6, true, 'pending'),
  ('funny moments', 7, true, 'pending'),
  ('funny moments youtube', 8, true, 'pending'),
  ('satisfying videos', 9, true, 'pending'),
  ('satisfying videos youtube', 10, true, 'pending'),
  ('sleep sounds', 11, true, 'pending'),
  ('sleep sounds youtube', 12, true, 'pending'),
  ('lofi streams', 13, true, 'pending'),
  ('lofi streams youtube', 14, true, 'pending'),
  ('livestream highlights', 15, true, 'pending'),
  ('livestream highlights youtube', 16, true, 'pending'),
  ('podcast clips', 17, true, 'pending'),
  ('podcast clips youtube', 18, true, 'pending'),
  ('breaking news explainers', 19, true, 'pending'),
  ('breaking news explainers youtube', 20, true, 'pending'),
  ('true crime stories', 21, true, 'pending'),
  ('true crime stories youtube', 22, true, 'pending'),
  ('interrogation breakdowns', 23, true, 'pending'),
  ('interrogation breakdowns youtube', 24, true, 'pending'),
  ('history explained', 25, true, 'pending'),
  ('history explained youtube', 26, true, 'pending'),
  ('science explainers', 27, true, 'pending'),
  ('science explainers youtube', 28, true, 'pending'),
  ('gadget reviews', 29, true, 'pending'),
  ('gadget reviews youtube', 30, true, 'pending'),
  ('phone comparisons', 31, true, 'pending'),
  ('phone comparisons youtube', 32, true, 'pending'),
  ('laptop reviews', 33, true, 'pending'),
  ('laptop reviews youtube', 34, true, 'pending'),
  ('camera reviews', 35, true, 'pending'),
  ('camera reviews youtube', 36, true, 'pending'),
  ('ev reviews', 37, true, 'pending'),
  ('ev reviews youtube', 38, true, 'pending'),
  ('truck builds', 39, true, 'pending'),
  ('truck builds youtube', 40, true, 'pending'),
  ('restoration videos', 41, true, 'pending'),
  ('restoration videos youtube', 42, true, 'pending'),
  ('detailing videos', 43, true, 'pending'),
  ('detailing videos youtube', 44, true, 'pending'),
  ('diy home projects', 45, true, 'pending'),
  ('diy home projects youtube', 46, true, 'pending'),
  ('woodworking', 47, true, 'pending'),
  ('woodworking youtube', 48, true, 'pending'),
  ('leatherworking', 49, true, 'pending'),
  ('leatherworking youtube', 50, true, 'pending'),
  ('crafts', 51, true, 'pending'),
  ('crafts youtube', 52, true, 'pending'),
  ('painting timelapse', 53, true, 'pending'),
  ('painting timelapse youtube', 54, true, 'pending'),
  ('drawing tutorials', 55, true, 'pending'),
  ('drawing tutorials youtube', 56, true, 'pending'),
  ('blender tutorials', 57, true, 'pending'),
  ('blender tutorials youtube', 58, true, 'pending'),
  ('coding tutorials', 59, true, 'pending'),
  ('coding tutorials youtube', 60, true, 'pending'),
  ('app development', 61, true, 'pending'),
  ('app development youtube', 62, true, 'pending'),
  ('game development', 63, true, 'pending'),
  ('game development youtube', 64, true, 'pending'),
  ('unreal engine tutorials', 65, true, 'pending'),
  ('unreal engine tutorials youtube', 66, true, 'pending'),
  ('unity tutorials', 67, true, 'pending'),
  ('unity tutorials youtube', 68, true, 'pending'),
  ('minecraft gameplay', 69, true, 'pending'),
  ('minecraft gameplay youtube', 70, true, 'pending'),
  ('roblox gameplay', 71, true, 'pending'),
  ('roblox gameplay youtube', 72, true, 'pending'),
  ('fortnite gameplay', 73, true, 'pending'),
  ('fortnite gameplay youtube', 74, true, 'pending'),
  ('gta roleplay', 75, true, 'pending'),
  ('gta roleplay youtube', 76, true, 'pending'),
  ('counter strike highlights', 77, true, 'pending'),
  ('counter strike highlights youtube', 78, true, 'pending'),
  ('valorant highlights', 79, true, 'pending'),
  ('valorant highlights youtube', 80, true, 'pending'),
  ('call of duty gameplay', 81, true, 'pending'),
  ('call of duty gameplay youtube', 82, true, 'pending'),
  ('fifa / ea fc gameplay', 83, true, 'pending'),
  ('fifa / ea fc gameplay youtube', 84, true, 'pending'),
  ('sports highlights', 85, true, 'pending'),
  ('sports highlights youtube', 86, true, 'pending'),
  ('nfl highlights', 87, true, 'pending'),
  ('nfl highlights youtube', 88, true, 'pending'),
  ('football (soccer) highlights', 89, true, 'pending'),
  ('football (soccer) highlights youtube', 90, true, 'pending'),
  ('ufc highlights', 91, true, 'pending'),
  ('ufc highlights youtube', 92, true, 'pending'),
  ('boxing highlights', 93, true, 'pending'),
  ('boxing highlights youtube', 94, true, 'pending'),
  ('wwe highlights', 95, true, 'pending'),
  ('wwe highlights youtube', 96, true, 'pending'),
  ('anime edits', 97, true, 'pending'),
  ('anime edits youtube', 98, true, 'pending'),
  ('anime explained', 99, true, 'pending'),
  ('anime explained youtube', 100, true, 'pending'),
  ('manga reviews', 101, true, 'pending'),
  ('manga reviews youtube', 102, true, 'pending'),
  ('one piece theory', 103, true, 'pending'),
  ('one piece theory youtube', 104, true, 'pending'),
  ('movie recaps', 105, true, 'pending'),
  ('movie recaps youtube', 106, true, 'pending'),
  ('movie ending explained', 107, true, 'pending'),
  ('movie ending explained youtube', 108, true, 'pending'),
  ('trailer breakdowns', 109, true, 'pending'),
  ('trailer breakdowns youtube', 110, true, 'pending'),
  ('tv show recaps', 111, true, 'pending'),
  ('tv show recaps youtube', 112, true, 'pending'),
  ('kpop mvs', 113, true, 'pending'),
  ('kpop mvs youtube', 114, true, 'pending'),
  ('rap music videos', 115, true, 'pending'),
  ('rap music videos youtube', 116, true, 'pending'),
  ('lyric videos', 117, true, 'pending'),
  ('lyric videos youtube', 118, true, 'pending'),
  ('dance challenges', 119, true, 'pending'),
  ('dance challenges youtube', 120, true, 'pending'),
  ('choreography videos', 121, true, 'pending'),
  ('choreography videos youtube', 122, true, 'pending'),
  ('cooking recipes', 123, true, 'pending'),
  ('cooking recipes youtube', 124, true, 'pending'),
  ('street food', 125, true, 'pending'),
  ('street food youtube', 126, true, 'pending'),
  ('mukbang', 127, true, 'pending'),
  ('mukbang youtube', 128, true, 'pending'),
  ('fitness routines', 129, true, 'pending'),
  ('fitness routines youtube', 130, true, 'pending'),
  ('home workouts', 131, true, 'pending'),
  ('home workouts youtube', 132, true, 'pending'),
  ('bodybuilding', 133, true, 'pending'),
  ('bodybuilding youtube', 134, true, 'pending'),
  ('skincare routines', 135, true, 'pending'),
  ('skincare routines youtube', 136, true, 'pending'),
  ('travel vlogs', 137, true, 'pending'),
  ('travel vlogs youtube', 138, true, 'pending'),
  ('japan travel', 139, true, 'pending'),
  ('japan travel youtube', 140, true, 'pending'),
  ('luxury home tours', 141, true, 'pending'),
  ('luxury home tours youtube', 142, true, 'pending'),
  ('study with me', 143, true, 'pending'),
  ('study with me youtube', 144, true, 'pending'),
  ('finance explainers', 145, true, 'pending'),
  ('finance explainers youtube', 146, true, 'pending'),
  ('investing basics', 147, true, 'pending'),
  ('investing basics youtube', 148, true, 'pending'),
  ('entrepreneurship stories', 149, true, 'pending'),
  ('entrepreneurship stories youtube', 150, true, 'pending'),
  ('mrbeast', 151, true, 'pending'),
  ('mrbeast youtube', 152, true, 'pending'),
  ('t-series', 153, true, 'pending'),
  ('t-series youtube', 154, true, 'pending'),
  ('cocomelon', 155, true, 'pending'),
  ('cocomelon youtube', 156, true, 'pending'),
  ('kids diana show', 157, true, 'pending'),
  ('kids diana show youtube', 158, true, 'pending'),
  ('vlad and niki', 159, true, 'pending'),
  ('vlad and niki youtube', 160, true, 'pending'),
  ('like nastya', 161, true, 'pending'),
  ('like nastya youtube', 162, true, 'pending'),
  ('stokes twins', 163, true, 'pending'),
  ('stokes twins youtube', 164, true, 'pending'),
  ('pewdiepie', 165, true, 'pending'),
  ('pewdiepie youtube', 166, true, 'pending'),
  ('dude perfect', 167, true, 'pending'),
  ('dude perfect youtube', 168, true, 'pending'),
  ('mark rober', 169, true, 'pending'),
  ('mark rober youtube', 170, true, 'pending'),
  ('sidemen', 171, true, 'pending'),
  ('sidemen youtube', 172, true, 'pending'),
  ('ksi', 173, true, 'pending'),
  ('ksi youtube', 174, true, 'pending'),
  ('ishowspeed', 175, true, 'pending'),
  ('ishowspeed youtube', 176, true, 'pending'),
  ('kai cenat', 177, true, 'pending'),
  ('kai cenat youtube', 178, true, 'pending'),
  ('ludwig', 179, true, 'pending'),
  ('ludwig youtube', 180, true, 'pending'),
  ('hasanabi', 181, true, 'pending'),
  ('hasanabi youtube', 182, true, 'pending'),
  ('asmongold', 183, true, 'pending'),
  ('asmongold youtube', 184, true, 'pending'),
  ('xqc', 185, true, 'pending'),
  ('xqc youtube', 186, true, 'pending'),
  ('pokimane', 187, true, 'pending'),
  ('pokimane youtube', 188, true, 'pending'),
  ('ninja', 189, true, 'pending'),
  ('ninja youtube', 190, true, 'pending'),
  ('drdisrespect', 191, true, 'pending'),
  ('drdisrespect youtube', 192, true, 'pending'),
  ('moistcr1tikal', 193, true, 'pending'),
  ('moistcr1tikal youtube', 194, true, 'pending'),
  ('juegagerman', 195, true, 'pending'),
  ('juegagerman youtube', 196, true, 'pending'),
  ('fernanfloo', 197, true, 'pending'),
  ('fernanfloo youtube', 198, true, 'pending'),
  ('elrubiusomg', 199, true, 'pending'),
  ('elrubiusomg youtube', 200, true, 'pending'),
  ('auronplay', 201, true, 'pending'),
  ('auronplay youtube', 202, true, 'pending'),
  ('ibai', 203, true, 'pending'),
  ('ibai youtube', 204, true, 'pending'),
  ('dream', 205, true, 'pending'),
  ('dream youtube', 206, true, 'pending'),
  ('technoblade', 207, true, 'pending'),
  ('technoblade youtube', 208, true, 'pending'),
  ('tommyinnit', 209, true, 'pending'),
  ('tommyinnit youtube', 210, true, 'pending'),
  ('dantdm', 211, true, 'pending'),
  ('dantdm youtube', 212, true, 'pending'),
  ('prestonplayz', 213, true, 'pending'),
  ('prestonplayz youtube', 214, true, 'pending'),
  ('unspeakable', 215, true, 'pending'),
  ('unspeakable youtube', 216, true, 'pending'),
  ('aphmau', 217, true, 'pending'),
  ('aphmau youtube', 218, true, 'pending'),
  ('lazarbeam', 219, true, 'pending'),
  ('lazarbeam youtube', 220, true, 'pending'),
  ('coryxkenshin', 221, true, 'pending'),
  ('coryxkenshin youtube', 222, true, 'pending'),
  ('vanossgaming', 223, true, 'pending'),
  ('vanossgaming youtube', 224, true, 'pending'),
  ('jacksepticeye', 225, true, 'pending'),
  ('jacksepticeye youtube', 226, true, 'pending'),
  ('logan paul', 227, true, 'pending'),
  ('logan paul youtube', 228, true, 'pending'),
  ('jake paul', 229, true, 'pending'),
  ('jake paul youtube', 230, true, 'pending'),
  ('joe rogan', 231, true, 'pending'),
  ('joe rogan youtube', 232, true, 'pending'),
  ('lex fridman', 233, true, 'pending'),
  ('lex fridman youtube', 234, true, 'pending'),
  ('andrew huberman', 235, true, 'pending'),
  ('andrew huberman youtube', 236, true, 'pending'),
  ('jordan peterson', 237, true, 'pending'),
  ('jordan peterson youtube', 238, true, 'pending'),
  ('ben shapiro', 239, true, 'pending'),
  ('ben shapiro youtube', 240, true, 'pending'),
  ('piers morgan', 241, true, 'pending'),
  ('piers morgan youtube', 242, true, 'pending'),
  ('philip defranco', 243, true, 'pending'),
  ('philip defranco youtube', 244, true, 'pending'),
  ('coldfusion', 245, true, 'pending'),
  ('coldfusion youtube', 246, true, 'pending'),
  ('marques brownlee', 247, true, 'pending'),
  ('marques brownlee youtube', 248, true, 'pending'),
  ('linus tech tips', 249, true, 'pending'),
  ('linus tech tips youtube', 250, true, 'pending'),
  ('mrwhosetheboss', 251, true, 'pending'),
  ('mrwhosetheboss youtube', 252, true, 'pending'),
  ('unbox therapy', 253, true, 'pending'),
  ('unbox therapy youtube', 254, true, 'pending'),
  ('veritasium', 255, true, 'pending'),
  ('veritasium youtube', 256, true, 'pending'),
  ('kurzgesagt', 257, true, 'pending'),
  ('kurzgesagt youtube', 258, true, 'pending'),
  ('smartereveryday', 259, true, 'pending'),
  ('smartereveryday youtube', 260, true, 'pending'),
  ('vsauce', 261, true, 'pending'),
  ('vsauce youtube', 262, true, 'pending'),
  ('nilered', 263, true, 'pending'),
  ('nilered youtube', 264, true, 'pending'),
  ('jazza', 265, true, 'pending'),
  ('jazza youtube', 266, true, 'pending'),
  ('proko', 267, true, 'pending'),
  ('proko youtube', 268, true, 'pending'),
  ('samdoesarts', 269, true, 'pending'),
  ('samdoesarts youtube', 270, true, 'pending'),
  ('wlop', 271, true, 'pending'),
  ('wlop youtube', 272, true, 'pending'),
  ('peter mckinnon', 273, true, 'pending'),
  ('peter mckinnon youtube', 274, true, 'pending'),
  ('casey neistat', 275, true, 'pending'),
  ('casey neistat youtube', 276, true, 'pending'),
  ('emma chamberlain', 277, true, 'pending'),
  ('emma chamberlain youtube', 278, true, 'pending'),
  ('yes theory', 279, true, 'pending'),
  ('yes theory youtube', 280, true, 'pending'),
  ('nelk', 281, true, 'pending'),
  ('nelk youtube', 282, true, 'pending'),
  ('airrack', 283, true, 'pending'),
  ('airrack youtube', 284, true, 'pending'),
  ('ryan trahan', 285, true, 'pending'),
  ('ryan trahan youtube', 286, true, 'pending'),
  ('good mythical morning', 287, true, 'pending'),
  ('good mythical morning youtube', 288, true, 'pending'),
  ('jubilee', 289, true, 'pending'),
  ('jubilee youtube', 290, true, 'pending'),
  ('cut', 291, true, 'pending'),
  ('cut youtube', 292, true, 'pending'),
  ('jubilee middle ground', 293, true, 'pending'),
  ('jubilee middle ground youtube', 294, true, 'pending'),
  ('wwe', 295, true, 'pending'),
  ('wwe youtube', 296, true, 'pending'),
  ('ufc', 297, true, 'pending'),
  ('ufc youtube', 298, true, 'pending'),
  ('nba', 299, true, 'pending'),
  ('nba youtube', 300, true, 'pending'),
  ('espn', 301, true, 'pending'),
  ('espn youtube', 302, true, 'pending'),
  ('dazn', 303, true, 'pending'),
  ('dazn youtube', 304, true, 'pending'),
  ('br football', 305, true, 'pending'),
  ('br football youtube', 306, true, 'pending'),
  ('star wars', 307, true, 'pending'),
  ('star wars youtube', 308, true, 'pending'),
  ('marvel entertainment', 309, true, 'pending'),
  ('marvel entertainment youtube', 310, true, 'pending'),
  ('abp news', 311, true, 'pending'),
  ('abp news youtube', 312, true, 'pending'),
  ('al jazeera english', 313, true, 'pending'),
  ('al jazeera english youtube', 314, true, 'pending'),
  ('bbc news', 315, true, 'pending'),
  ('bbc news youtube', 316, true, 'pending'),
  ('mrbeast challenge', 317, true, 'pending'),
  ('mrbeast challenge youtube', 318, true, 'pending'),
  ('mrbeast newest video', 319, true, 'pending'),
  ('mrbeast newest video youtube', 320, true, 'pending'),
  ('sidemen challenge', 321, true, 'pending'),
  ('sidemen challenge youtube', 322, true, 'pending'),
  ('sidemen among us', 323, true, 'pending'),
  ('sidemen among us youtube', 324, true, 'pending'),
  ('ludwig stream clips', 325, true, 'pending'),
  ('ludwig stream clips youtube', 326, true, 'pending'),
  ('hasanabi debate', 327, true, 'pending'),
  ('hasanabi debate youtube', 328, true, 'pending'),
  ('asmongold reaction', 329, true, 'pending'),
  ('asmongold reaction youtube', 330, true, 'pending'),
  ('ishowspeed funny moments', 331, true, 'pending'),
  ('ishowspeed funny moments youtube', 332, true, 'pending'),
  ('kai cenat stream highlights', 333, true, 'pending'),
  ('kai cenat stream highlights youtube', 334, true, 'pending'),
  ('joe rogan podcast clips', 335, true, 'pending'),
  ('joe rogan podcast clips youtube', 336, true, 'pending'),
  ('internet drama explained', 337, true, 'pending'),
  ('internet drama explained youtube', 338, true, 'pending'),
  ('streamer drama today', 339, true, 'pending'),
  ('streamer drama today youtube', 340, true, 'pending'),
  ('twitch drama clips', 341, true, 'pending'),
  ('twitch drama clips youtube', 342, true, 'pending'),
  ('youtube drama roundup', 343, true, 'pending'),
  ('youtube drama roundup latest', 344, true, 'pending'),
  ('influencer apology', 345, true, 'pending'),
  ('influencer apology youtube', 346, true, 'pending'),
  ('celebrity feud explained', 347, true, 'pending'),
  ('celebrity feud explained youtube', 348, true, 'pending'),
  ('fortnite update', 349, true, 'pending'),
  ('fortnite update youtube', 350, true, 'pending'),
  ('fortnite live event', 351, true, 'pending'),
  ('fortnite live event youtube', 352, true, 'pending'),
  ('fortnite ranked highlights', 353, true, 'pending'),
  ('fortnite ranked highlights youtube', 354, true, 'pending'),
  ('minecraft 100 days', 355, true, 'pending'),
  ('minecraft 100 days youtube', 356, true, 'pending'),
  ('minecraft hardcore', 357, true, 'pending'),
  ('minecraft hardcore youtube', 358, true, 'pending'),
  ('roblox brookhaven', 359, true, 'pending'),
  ('roblox brookhaven youtube', 360, true, 'pending'),
  ('gta 6 news', 361, true, 'pending'),
  ('gta 6 news youtube', 362, true, 'pending'),
  ('gta rp moments', 363, true, 'pending'),
  ('gta rp moments youtube', 364, true, 'pending'),
  ('counter strike 2 highlights', 365, true, 'pending'),
  ('counter strike 2 highlights youtube', 366, true, 'pending'),
  ('valorant pro highlights', 367, true, 'pending'),
  ('valorant pro highlights youtube', 368, true, 'pending'),
  ('call of duty warzone highlights', 369, true, 'pending'),
  ('call of duty warzone highlights youtube', 370, true, 'pending'),
  ('fifa / ea fc career mode', 371, true, 'pending'),
  ('fifa / ea fc career mode youtube', 372, true, 'pending'),
  ('nba game highlights', 373, true, 'pending'),
  ('nba game highlights youtube', 374, true, 'pending'),
  ('nba playoffs highlights', 375, true, 'pending'),
  ('nba playoffs highlights youtube', 376, true, 'pending'),
  ('nfl highlights today', 377, true, 'pending'),
  ('nfl highlights today youtube', 378, true, 'pending'),
  ('champions league highlights', 379, true, 'pending'),
  ('champions league highlights youtube', 380, true, 'pending'),
  ('premier league highlights', 381, true, 'pending'),
  ('premier league highlights youtube', 382, true, 'pending'),
  ('ufc full fight highlights', 383, true, 'pending'),
  ('ufc full fight highlights youtube', 384, true, 'pending'),
  ('wwe raw highlights', 385, true, 'pending'),
  ('wwe raw highlights youtube', 386, true, 'pending'),
  ('boxing face off', 387, true, 'pending'),
  ('boxing face off youtube', 388, true, 'pending'),
  ('one piece chapter review', 389, true, 'pending'),
  ('one piece chapter review youtube', 390, true, 'pending'),
  ('jujutsu kaisen explained', 391, true, 'pending'),
  ('jujutsu kaisen explained youtube', 392, true, 'pending'),
  ('demon slayer edits', 393, true, 'pending'),
  ('demon slayer edits youtube', 394, true, 'pending'),
  ('attack on titan ending explained', 395, true, 'pending'),
  ('attack on titan ending explained youtube', 396, true, 'pending'),
  ('star wars theory', 397, true, 'pending'),
  ('star wars theory youtube', 398, true, 'pending'),
  ('marvel breakdown', 399, true, 'pending'),
  ('marvel breakdown youtube', 400, true, 'pending'),
  ('trailer reaction', 401, true, 'pending'),
  ('trailer reaction youtube', 402, true, 'pending'),
  ('netflix series recap', 403, true, 'pending'),
  ('netflix series recap youtube', 404, true, 'pending'),
  ('anime top 10', 405, true, 'pending'),
  ('anime top 10 youtube', 406, true, 'pending'),
  ('kdrama recap', 407, true, 'pending'),
  ('kdrama recap youtube', 408, true, 'pending'),
  ('kpop comeback', 409, true, 'pending'),
  ('kpop comeback youtube', 410, true, 'pending'),
  ('blackpink performance', 411, true, 'pending'),
  ('blackpink performance youtube', 412, true, 'pending'),
  ('bts live performance', 413, true, 'pending'),
  ('bts live performance youtube', 414, true, 'pending'),
  ('taylor swift live', 415, true, 'pending'),
  ('taylor swift live youtube', 416, true, 'pending'),
  ('diss track reaction', 417, true, 'pending'),
  ('diss track reaction youtube', 418, true, 'pending'),
  ('funny ad compilation', 419, true, 'pending'),
  ('funny ad compilation youtube', 420, true, 'pending'),
  ('best commercials', 421, true, 'pending'),
  ('best commercials youtube', 422, true, 'pending'),
  ('cringe ads reaction', 423, true, 'pending'),
  ('cringe ads reaction youtube', 424, true, 'pending'),
  ('car review 2026', 425, true, 'pending'),
  ('car review 2026 youtube', 426, true, 'pending'),
  ('best electric suv', 427, true, 'pending'),
  ('best electric suv youtube', 428, true, 'pending'),
  ('iphone review', 429, true, 'pending'),
  ('iphone review youtube', 430, true, 'pending'),
  ('samsung comparison', 431, true, 'pending'),
  ('samsung comparison youtube', 432, true, 'pending'),
  ('budget phone comparison', 433, true, 'pending'),
  ('budget phone comparison youtube', 434, true, 'pending'),
  ('camera test', 435, true, 'pending'),
  ('camera test youtube', 436, true, 'pending'),
  ('ai tools tutorial', 437, true, 'pending'),
  ('ai tools tutorial youtube', 438, true, 'pending'),
  ('chatgpt tutorial', 439, true, 'pending'),
  ('chatgpt tutorial youtube', 440, true, 'pending'),
  ('coding project tutorial', 441, true, 'pending'),
  ('coding project tutorial youtube', 442, true, 'pending'),
  ('blender beginner tutorial', 443, true, 'pending'),
  ('blender beginner tutorial youtube', 444, true, 'pending'),
  ('unreal engine project', 445, true, 'pending'),
  ('unreal engine project youtube', 446, true, 'pending'),
  ('unity game dev', 447, true, 'pending'),
  ('unity game dev youtube', 448, true, 'pending'),
  ('finance news today', 449, true, 'pending'),
  ('finance news today youtube', 450, true, 'pending'),
  ('stock market recap', 451, true, 'pending'),
  ('stock market recap youtube', 452, true, 'pending'),
  ('crypto news today', 453, true, 'pending'),
  ('crypto news today youtube', 454, true, 'pending'),
  ('business documentary', 455, true, 'pending'),
  ('business documentary youtube', 456, true, 'pending'),
  ('startup breakdown', 457, true, 'pending'),
  ('startup breakdown youtube', 458, true, 'pending'),
  ('productivity routine', 459, true, 'pending'),
  ('productivity routine youtube', 460, true, 'pending'),
  ('study with me pomodoro', 461, true, 'pending'),
  ('study with me pomodoro youtube', 462, true, 'pending'),
  ('morning routine', 463, true, 'pending'),
  ('morning routine youtube', 464, true, 'pending'),
  ('glow up transformation', 465, true, 'pending'),
  ('glow up transformation youtube', 466, true, 'pending'),
  ('makeup tutorial', 467, true, 'pending'),
  ('makeup tutorial youtube', 468, true, 'pending'),
  ('skincare routine', 469, true, 'pending'),
  ('skincare routine youtube', 470, true, 'pending'),
  ('hair tutorial', 471, true, 'pending'),
  ('hair tutorial youtube', 472, true, 'pending'),
  ('outfit ideas', 473, true, 'pending'),
  ('outfit ideas youtube', 474, true, 'pending'),
  ('thrift flip', 475, true, 'pending'),
  ('thrift flip youtube', 476, true, 'pending'),
  ('meal prep recipes', 477, true, 'pending'),
  ('meal prep recipes youtube', 478, true, 'pending'),
  ('street food tour', 479, true, 'pending'),
  ('street food tour youtube', 480, true, 'pending'),
  ('mukbang spicy noodles', 481, true, 'pending'),
  ('mukbang spicy noodles youtube', 482, true, 'pending'),
  ('japan travel guide', 483, true, 'pending'),
  ('japan travel guide youtube', 484, true, 'pending'),
  ('tokyo vlog', 485, true, 'pending'),
  ('tokyo vlog youtube', 486, true, 'pending'),
  ('china travel vlog', 487, true, 'pending'),
  ('china travel vlog youtube', 488, true, 'pending'),
  ('europe budget travel', 489, true, 'pending'),
  ('europe budget travel youtube', 490, true, 'pending'),
  ('hotel review', 491, true, 'pending'),
  ('hotel review youtube', 492, true, 'pending'),
  ('true crime documentary', 493, true, 'pending'),
  ('true crime documentary youtube', 494, true, 'pending'),
  ('interrogation analysis', 495, true, 'pending'),
  ('interrogation analysis youtube', 496, true, 'pending'),
  ('courtroom breakdown', 497, true, 'pending'),
  ('courtroom breakdown youtube', 498, true, 'pending'),
  ('mystery iceberg', 499, true, 'pending'),
  ('mystery iceberg youtube', 500, true, 'pending'),
  ('conspiracy iceberg', 501, true, 'pending'),
  ('conspiracy iceberg youtube', 502, true, 'pending'),
  ('political debate clips', 503, true, 'pending'),
  ('political debate clips youtube', 504, true, 'pending'),
  ('election explained', 505, true, 'pending'),
  ('election explained youtube', 506, true, 'pending'),
  ('geopolitics explained', 507, true, 'pending'),
  ('geopolitics explained youtube', 508, true, 'pending'),
  ('war update analysis', 509, true, 'pending'),
  ('war update analysis youtube', 510, true, 'pending'),
  ('history documentary', 511, true, 'pending'),
  ('history documentary youtube', 512, true, 'pending'),
  ('science experiment', 513, true, 'pending'),
  ('science experiment youtube', 514, true, 'pending'),
  ('space mission update', 515, true, 'pending'),
  ('space mission update youtube', 516, true, 'pending'),
  ('hindi gaming', 517, true, 'pending'),
  ('hindi gaming youtube', 518, true, 'pending'),
  ('hindi news debate', 519, true, 'pending'),
  ('hindi news debate youtube', 520, true, 'pending'),
  ('spanish football highlights', 521, true, 'pending'),
  ('spanish football highlights youtube', 522, true, 'pending'),
  ('spanish streamer clips', 523, true, 'pending'),
  ('spanish streamer clips youtube', 524, true, 'pending'),
  ('brazil funk music video', 525, true, 'pending'),
  ('brazil funk music video youtube', 526, true, 'pending'),
  ('arabic news explainer', 527, true, 'pending'),
  ('arabic news explainer youtube', 528, true, 'pending'),
  ('japanese anime edits', 529, true, 'pending'),
  ('japanese anime edits youtube', 530, true, 'pending'),
  ('korean variety clips', 531, true, 'pending'),
  ('korean variety clips youtube', 532, true, 'pending'),
  ('indonesian prank videos', 533, true, 'pending'),
  ('indonesian prank videos youtube', 534, true, 'pending'),
  ('filipino vlogs', 535, true, 'pending'),
  ('filipino vlogs youtube', 536, true, 'pending'),
  ('turkish drama clips', 537, true, 'pending'),
  ('turkish drama clips youtube', 538, true, 'pending'),
  ('german tech reviews', 539, true, 'pending'),
  ('german tech reviews youtube', 540, true, 'pending'),
  ('french street interviews', 541, true, 'pending'),
  ('french street interviews youtube', 542, true, 'pending'),
  ('russian gaming highlights', 543, true, 'pending'),
  ('russian gaming highlights youtube', 544, true, 'pending')
on conflict (query_text) do nothing;
